name: Workflow 1
on: push
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: install all the dependence
        run: npm ci
      - name: run the lint
        run: npm run lint
      - name: run the test
        run: npm run test
      - name: run the build
        run: npm run build
