name: Deployment exercise one
on: push
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get the code inside the Workflow
        uses: actions/checkout@v3
      - name: install all the dependence
        run: npm install
      - name: run the lint
        run: npm run lint
      - name: run the test
        run: npm run test
      - name: run the build
        run: npm run build
