name: Workflow 1
on: push
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get the code inside the Workflow
        run: actions/checkout@v3
      - name: install all the dependence
        run: npm install
      - name: run the lint
        run: npm run lint
      - name: run the test
        run: npm run test
      - name: run the build
        run: npm run build
